export type Video = {
  id: number;
  user_id: number;
  hls_url: string | null;
  category_id: number;
  temp_url: string;
  url: string | null;
  transfer_status: number;
  upload_status: number;
  cover: string;
  duration: number | null;
  sequence: number | null;
  isDeleted: boolean;
  ref: string;
  user?: { id: number; username: string };
  category?: { name: string };
  subCategory?: { name: string };
  public_urls?: { cover_url: string };
  createdAt: string;
  checking?: string;
  comment?: string;
  cover_upload_status?: number;
  updatedAt?: string;
};